name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-selfhosted-1:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 60
    env:
      SHARD_INDEX: 1
      SHARD_TOTAL: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --shard=$SHARD_INDEX/$SHARD_TOTAL
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-1
          path: playwright-report/

  test-selfhosted-2:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 60
    env:
      SHARD_INDEX: 2
      SHARD_TOTAL: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --shard=$SHARD_INDEX/$SHARD_TOTAL
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-2
          path: playwright-report/

  test-github-hosted:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 60
    env:
      SHARD_INDEX: 3
      SHARD_TOTAL: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --shard=$SHARD_INDEX/$SHARD_TOTAL
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-3
          path: playwright-report/
